---
- name: Install security patches on AKS nodes
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    resource_group_name: "my-resource-group"
    aks_name: "my-aks-cluster"

  tasks:
    - name: Get AKS nodes IP addresses
      azure_rm_aks_info:
        resource_group: "{{ resource_group_name }}"
        name: "{{ aks_name }}"
        get_ssh_key: no
        show_details: no
      register: aks_info

    - name: Add AKS nodes to inventory
      add_host:
        name: "{{ item.properties.fqdn }}"
        ansible_host: "{{ item.properties.ipAddress }}"
        ansible_user: azureuser
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items: "{{ aks_info.agent_pools[0].leaf_nodes }}"

    - name: Install security updates
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
        only_security: yes
      with_items:
        - security

    - name: Reboot nodes if needed
      reboot:
        reboot_timeout: 3600
        post_reboot_delay: 30
      when: ansible_reboot_pending | default(false)
